### ISSUE TITLE
Add block caching

### ISSUE THREAD

**Issue by kayakr** [mjordan/islandora_whole_object#16]
e.g. in `IslandoraWholeObjectFedoraBlock`
```
  /**
   * {@inheritdoc}
   */
  public function getCacheTags() {
    $node = \Drupal::routeMatch()->getParameter('node');
    return Cache::mergeTags(parent::getCacheTags(), ["node:{$node->id()}"]);
  }
```
I found I was getting reports of RDF from fcrepo that related to a different object.

**Comment by mjordan** [comment]
Tested and works for me; if you have time, pull in master, test, and close. Thanks very much!

**Comment by mjordan** [comment]
This seems to be working. If not, please reopen.
